apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"load-balancer-example"},"name":"edureka-actual","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app.kubernetes.io/name":"load-balancer-example"}},"template":{"metadata":{"labels":{"app.kubernetes.io/name":"load-balancer-example"}},"spec":{"containers":[{"image":"ife1812/edureka-actual:0.0.1","name":"edureka-actual","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2022-09-15T18:29:24Z"
  generation: 1
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: edureka-actual
  namespace: default
  resourceVersion: "9333"
  uid: c5a8b7f8-1d44-457e-a985-daed2f9c2afd
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - image: ife1812/edureka-actual:0.0.1
        imagePullPolicy: IfNotPresent
        name: edureka-actual
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-09-15T18:29:56Z"
    lastUpdateTime: "2022-09-15T18:29:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-09-15T18:29:24Z"
    lastUpdateTime: "2022-09-15T18:29:56Z"
    message: ReplicaSet "edureka-actual-5bc67f8665" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
