apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-15T18:31:20Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/name: load-balancer-example
  name: my-service
  namespace: default
  resourceVersion: "9584"
  uid: 0b6ab98b-ba67-4dbb-b159-f2628f6886ed
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 172.20.73.10
  clusterIPs:
  - 172.20.73.10
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31879
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: load-balancer-example
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: a0b6ab98bba674dbbb159f2628f6886e-1649676298.us-east-1.elb.amazonaws.com
